#!/usr/bin/env php
<?php
  $db = pg_Connect('host=localhost user=postgres dbname=production');
  $interval = 10;
  
  echo "Initializing...\n";
  $sql = "SELECT schemaname || '.' || relname, (n_tup_ins + n_tup_upd + n_tup_del) FROM pg_stat_user_tables";
  $result = pg_query($db, $sql);
  $rows = pg_num_rows($result);
  $counter = array();
  for ( $y = 0; $y < $rows; $y++ )
  {
    $counter[pg_Fetch_Result($result, $y, 0)] = intval(pg_Fetch_Result($result, $y, 1));
  }

  while ( 1 )
  {
    sleep($interval);
    system('clear');
    echo "Heavy Writers - " . strftime('%x %X') . " - Interval: " . $interval . "s\n";
    echo "----------------------------------------------------------------------------------\n";
    echo str_pad('Table', 40, ' ') . str_pad('Last Difference', 20, ' ', STR_PAD_LEFT) . str_pad('Total Writes', 20, ' ', STR_PAD_LEFT) . "\n";
    echo "----------------------------------------------------------------------------------\n";
    $result = pg_query($db, $sql);
    $rows = pg_num_rows($result);
    $last = array();
    $names = array();
    for ( $y = 0; $y < $rows; $y++ )
    {
      $name = pg_fetch_result($result, $y, 0);
      $count = pg_fetch_result($result, $y, 1);
      $last[$y] = intval($count) - intval($counter[$name]);
      $names[$y] = $name;
      $counter[$name] = intval($count);
  
    }

    array_multisort($last, SORT_DESC, $names);
 
    $max = count($last);
    if ( ( $max ) > 20 ) $max = 20;
    for ( $y = 0; $y < $max; $y++ )
      echo str_pad(($y + 1) . '.', 4, ' ')  . str_pad($names[$y], 36, ' ', STR_PAD_RIGHT) . str_pad($last[$y], 20, ' ', STR_PAD_LEFT) . str_pad($counter[$names[$y]], 20, ' ', STR_PAD_LEFT) . "\n";
  
  }
